/**
 * Nordea Open Banking API
 * Open Banking API
 *
 * OpenAPI spec version: 2.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AccountInfo', 'model/Link'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./AccountInfo'), require('./Link'));
  } else {
    // Browser globals (root is window)
    if (!root.NordeaOpenBankingApi) {
      root.NordeaOpenBankingApi = {};
    }
    root.NordeaOpenBankingApi.AccountList = factory(root.NordeaOpenBankingApi.ApiClient, root.NordeaOpenBankingApi.AccountInfo, root.NordeaOpenBankingApi.Link);
  }
}(this, function(ApiClient, AccountInfo, Link) {
  'use strict';




  /**
   * The AccountList model module.
   * @module model/AccountList
   * @version 2.2
   */

  /**
   * Constructs a new <code>AccountList</code>.
   * List of accounts
   * @alias module:model/AccountList
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>AccountList</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AccountList} obj Optional instance to populate.
   * @return {module:model/AccountList} The populated <code>AccountList</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('_links')) {
        obj['_links'] = ApiClient.convertToType(data['_links'], [Link]);
      }
      if (data.hasOwnProperty('accounts')) {
        obj['accounts'] = ApiClient.convertToType(data['accounts'], [AccountInfo]);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/Link>} _links
   */
  exports.prototype['_links'] = undefined;
  /**
   * List of accounts
   * @member {Array.<module:model/AccountInfo>} accounts
   */
  exports.prototype['accounts'] = undefined;



  return exports;
}));


