/**
 * Nordea Open Banking API
 * Open Banking API
 *
 * OpenAPI spec version: 2.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AccountList', 'model/ExternalResponseHeader'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./AccountList'), require('./ExternalResponseHeader'));
  } else {
    // Browser globals (root is window)
    if (!root.NordeaOpenBankingApi) {
      root.NordeaOpenBankingApi = {};
    }
    root.NordeaOpenBankingApi.AccountListResponse = factory(root.NordeaOpenBankingApi.ApiClient, root.NordeaOpenBankingApi.AccountList, root.NordeaOpenBankingApi.ExternalResponseHeader);
  }
}(this, function(ApiClient, AccountList, ExternalResponseHeader) {
  'use strict';




  /**
   * The AccountListResponse model module.
   * @module model/AccountListResponse
   * @version 2.2
   */

  /**
   * Constructs a new <code>AccountListResponse</code>.
   * Account list response
   * @alias module:model/AccountListResponse
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>AccountListResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AccountListResponse} obj Optional instance to populate.
   * @return {module:model/AccountListResponse} The populated <code>AccountListResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('groupHeader')) {
        obj['groupHeader'] = ExternalResponseHeader.constructFromObject(data['groupHeader']);
      }
      if (data.hasOwnProperty('response')) {
        obj['response'] = AccountList.constructFromObject(data['response']);
      }
    }
    return obj;
  }

  /**
   * Standard format response header structure
   * @member {module:model/ExternalResponseHeader} groupHeader
   */
  exports.prototype['groupHeader'] = undefined;
  /**
   * Listed accounts
   * @member {module:model/AccountList} response
   */
  exports.prototype['response'] = undefined;



  return exports;
}));


