/**
 * Nordea Open Banking API
 * Open Banking API
 *
 * OpenAPI spec version: 2.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.NordeaOpenBankingApi) {
      root.NordeaOpenBankingApi = {};
    }
    root.NordeaOpenBankingApi.BankInfo = factory(root.NordeaOpenBankingApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The BankInfo model module.
   * @module model/BankInfo
   * @version 2.2
   */

  /**
   * Constructs a new <code>BankInfo</code>.
   * @alias module:model/BankInfo
   * @class
   * @param bic {String} Business Identifier Code of account servicing institution according to ISO 9362.
   * @param country {String} Country code according to ISO Alpha-2
   * @param name {String} Unit name
   */
  var exports = function(bic, country, name) {
    var _this = this;

    _this['bic'] = bic;
    _this['country'] = country;
    _this['name'] = name;
  };

  /**
   * Constructs a <code>BankInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BankInfo} obj Optional instance to populate.
   * @return {module:model/BankInfo} The populated <code>BankInfo</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('bic')) {
        obj['bic'] = ApiClient.convertToType(data['bic'], 'String');
      }
      if (data.hasOwnProperty('country')) {
        obj['country'] = ApiClient.convertToType(data['country'], 'String');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
    }
    return obj;
  }

  /**
   * Business Identifier Code of account servicing institution according to ISO 9362.
   * @member {String} bic
   */
  exports.prototype['bic'] = undefined;
  /**
   * Country code according to ISO Alpha-2
   * @member {String} country
   */
  exports.prototype['country'] = undefined;
  /**
   * Unit name
   * @member {String} name
   */
  exports.prototype['name'] = undefined;



  return exports;
}));


