/**
 * Nordea Open Banking API
 * Open Banking API
 *
 * OpenAPI spec version: 2.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Pagination'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Pagination'));
  } else {
    // Browser globals (root is window)
    if (!root.NordeaOpenBankingApi) {
      root.NordeaOpenBankingApi = {};
    }
    root.NordeaOpenBankingApi.ExternalResponseHeader = factory(root.NordeaOpenBankingApi.ApiClient, root.NordeaOpenBankingApi.Pagination);
  }
}(this, function(ApiClient, Pagination) {
  'use strict';




  /**
   * The ExternalResponseHeader model module.
   * @module model/ExternalResponseHeader
   * @version 2.2
   */

  /**
   * Constructs a new <code>ExternalResponseHeader</code>.
   * External response header
   * @alias module:model/ExternalResponseHeader
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>ExternalResponseHeader</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ExternalResponseHeader} obj Optional instance to populate.
   * @return {module:model/ExternalResponseHeader} The populated <code>ExternalResponseHeader</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('creationDateTime')) {
        obj['creationDateTime'] = ApiClient.convertToType(data['creationDateTime'], 'Date');
      }
      if (data.hasOwnProperty('httpCode')) {
        obj['httpCode'] = ApiClient.convertToType(data['httpCode'], 'Number');
      }
      if (data.hasOwnProperty('messageIdentification')) {
        obj['messageIdentification'] = ApiClient.convertToType(data['messageIdentification'], 'String');
      }
      if (data.hasOwnProperty('messagePagination')) {
        obj['messagePagination'] = Pagination.constructFromObject(data['messagePagination']);
      }
    }
    return obj;
  }

  /**
   * Response creation time
   * @member {Date} creationDateTime
   */
  exports.prototype['creationDateTime'] = undefined;
  /**
   * HTTP code for response
   * @member {Number} httpCode
   */
  exports.prototype['httpCode'] = undefined;
  /**
   * Original request id for correlation purposes
   * @member {String} messageIdentification
   */
  exports.prototype['messageIdentification'] = undefined;
  /**
   * Details of paginated response
   * @member {module:model/Pagination} messagePagination
   */
  exports.prototype['messagePagination'] = undefined;



  return exports;
}));


