/**
 * Nordea Open Banking API
 * Open Banking API
 *
 * OpenAPI spec version: 2.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ExternalFailure', 'model/ExternalRequestEcho'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ExternalFailure'), require('./ExternalRequestEcho'));
  } else {
    // Browser globals (root is window)
    if (!root.NordeaOpenBankingApi) {
      root.NordeaOpenBankingApi = {};
    }
    root.NordeaOpenBankingApi.ExternalError = factory(root.NordeaOpenBankingApi.ApiClient, root.NordeaOpenBankingApi.ExternalFailure, root.NordeaOpenBankingApi.ExternalRequestEcho);
  }
}(this, function(ApiClient, ExternalFailure, ExternalRequestEcho) {
  'use strict';




  /**
   * The ExternalError model module.
   * @module model/ExternalError
   * @version 2.2
   */

  /**
   * Constructs a new <code>ExternalError</code>.
   * Error information
   * @alias module:model/ExternalError
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>ExternalError</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ExternalError} obj Optional instance to populate.
   * @return {module:model/ExternalError} The populated <code>ExternalError</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('failures')) {
        obj['failures'] = ApiClient.convertToType(data['failures'], [ExternalFailure]);
      }
      if (data.hasOwnProperty('httpCode')) {
        obj['httpCode'] = ApiClient.convertToType(data['httpCode'], 'Number');
      }
      if (data.hasOwnProperty('request')) {
        obj['request'] = ExternalRequestEcho.constructFromObject(data['request']);
      }
    }
    return obj;
  }

  /**
   * More details on the occurred error
   * @member {Array.<module:model/ExternalFailure>} failures
   */
  exports.prototype['failures'] = undefined;
  /**
   * HTTP error for response
   * @member {Number} httpCode
   */
  exports.prototype['httpCode'] = undefined;
  /**
   * Error details
   * @member {module:model/ExternalRequestEcho} request
   */
  exports.prototype['request'] = undefined;



  return exports;
}));


