/**
 * Nordea Open Banking API
 * Open Banking API
 *
 * OpenAPI spec version: 2.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.NordeaOpenBankingApi) {
      root.NordeaOpenBankingApi = {};
    }
    root.NordeaOpenBankingApi.ExternalRequestEcho = factory(root.NordeaOpenBankingApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ExternalRequestEcho model module.
   * @module model/ExternalRequestEcho
   * @version 2.2
   */

  /**
   * Constructs a new <code>ExternalRequestEcho</code>.
   * Original request information
   * @alias module:model/ExternalRequestEcho
   * @class
   * @param messageIdentifier {String} Original request id for correlation purposes
   */
  var exports = function(messageIdentifier) {
    var _this = this;

    _this['messageIdentifier'] = messageIdentifier;

  };

  /**
   * Constructs a <code>ExternalRequestEcho</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ExternalRequestEcho} obj Optional instance to populate.
   * @return {module:model/ExternalRequestEcho} The populated <code>ExternalRequestEcho</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('messageIdentifier')) {
        obj['messageIdentifier'] = ApiClient.convertToType(data['messageIdentifier'], 'String');
      }
      if (data.hasOwnProperty('url')) {
        obj['url'] = ApiClient.convertToType(data['url'], 'String');
      }
    }
    return obj;
  }

  /**
   * Original request id for correlation purposes
   * @member {String} messageIdentifier
   */
  exports.prototype['messageIdentifier'] = undefined;
  /**
   * Original request url
   * @member {String} url
   */
  exports.prototype['url'] = undefined;



  return exports;
}));


