/**
 * Nordea Open Banking API
 * Open Banking API
 *
 * OpenAPI spec version: 2.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.NordeaOpenBankingApi) {
      root.NordeaOpenBankingApi = {};
    }
    root.NordeaOpenBankingApi.Link = factory(root.NordeaOpenBankingApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Link model module.
   * @module model/Link
   * @version 2.2
   */

  /**
   * Constructs a new <code>Link</code>.
   * Context specific link (only GET supported)
   * @alias module:model/Link
   * @class
   * @param href {String} Relative path to the linked resource
   * @param rel {String} Describes the nature of the link, e.g. 'details' for a link to the detailed information of a listed resource.
   */
  var exports = function(href, rel) {
    var _this = this;

    _this['href'] = href;
    _this['rel'] = rel;
  };

  /**
   * Constructs a <code>Link</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Link} obj Optional instance to populate.
   * @return {module:model/Link} The populated <code>Link</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('href')) {
        obj['href'] = ApiClient.convertToType(data['href'], 'String');
      }
      if (data.hasOwnProperty('rel')) {
        obj['rel'] = ApiClient.convertToType(data['rel'], 'String');
      }
    }
    return obj;
  }

  /**
   * Relative path to the linked resource
   * @member {String} href
   */
  exports.prototype['href'] = undefined;
  /**
   * Describes the nature of the link, e.g. 'details' for a link to the detailed information of a listed resource.
   * @member {String} rel
   */
  exports.prototype['rel'] = undefined;



  return exports;
}));


