/**
 * Nordea Open Banking API
 * Open Banking API
 *
 * OpenAPI spec version: 2.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Link', 'model/Transaction'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Link'), require('./Transaction'));
  } else {
    // Browser globals (root is window)
    if (!root.NordeaOpenBankingApi) {
      root.NordeaOpenBankingApi = {};
    }
    root.NordeaOpenBankingApi.TransactionList = factory(root.NordeaOpenBankingApi.ApiClient, root.NordeaOpenBankingApi.Link, root.NordeaOpenBankingApi.Transaction);
  }
}(this, function(ApiClient, Link, Transaction) {
  'use strict';




  /**
   * The TransactionList model module.
   * @module model/TransactionList
   * @version 2.2
   */

  /**
   * Constructs a new <code>TransactionList</code>.
   * List of transactions
   * @alias module:model/TransactionList
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>TransactionList</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TransactionList} obj Optional instance to populate.
   * @return {module:model/TransactionList} The populated <code>TransactionList</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('_continuationKey')) {
        obj['_continuationKey'] = ApiClient.convertToType(data['_continuationKey'], 'String');
      }
      if (data.hasOwnProperty('_links')) {
        obj['_links'] = ApiClient.convertToType(data['_links'], [Link]);
      }
      if (data.hasOwnProperty('transactions')) {
        obj['transactions'] = ApiClient.convertToType(data['transactions'], [Transaction]);
      }
    }
    return obj;
  }

  /**
   * Key to subsequent page of transaction history
   * @member {String} _continuationKey
   */
  exports.prototype['_continuationKey'] = undefined;
  /**
   * Links to next page (if available) and self to restart the search
   * @member {Array.<module:model/Link>} _links
   */
  exports.prototype['_links'] = undefined;
  /**
   * Listed transactions
   * @member {Array.<module:model/Transaction>} transactions
   */
  exports.prototype['transactions'] = undefined;



  return exports;
}));


